Added Docker suppport for Server
CTR-tools/CTR-ModSDK pull request #141
Opened 2024-06-05 00:19 UTC by nomadics9

simple docker for ctr_srv for easy deployment on any system.

2024-06-05 08:56 UTC, aalhendi requested changes

2024-06-05 08:56 UTC, aalhendi commented on mods/Windows/OnlineCTR/Network_PC/Server/Dockerfile
> +RUN apt-get update && apt-get install -y cmake make gcc libenet-dev libtool autoconf automake build-essential
no need for make and gcc as they are a part of build-essential.

2024-06-05 08:56 UTC, aalhendi commented on mods/Windows/OnlineCTR/Network_PC/Server/buildDocker.sh
> +#have to git add . in NixOS
This seems to be nixos specific. Git add <.> is also very broad. Heres a suggestion:
```sh
# Check if the OS is NixOS
if [ "$(uname -s)" == "Linux" ] && grep -q 'NixOS' /etc/issue; then
    # NixOS-specific commands
    git add enet decompile
    rm ./enet/.git
    rm -r ./enet/.github
fi
```

2024-06-05 08:56 UTC, aalhendi commented on mods/Windows/OnlineCTR/Network_PC/Server/buildDocker.sh
> +git add .
same as above:
```sh
# Reverse the git add (only on NixOS)
if [ "$(uname -s)" == "Linux" ] && grep -q 'NixOS' /etc/issue; then
    git reset HEAD enet decompile
fi
```

2024-06-05 08:56 UTC, aalhendi commented on mods/Windows/OnlineCTR/Network_PC/Server/buildDocker.sh
> +sleep 2
sleep needed?

2024-06-05 08:56 UTC, aalhendi commented on mods/Windows/OnlineCTR/Network_PC/Server/buildDocker.sh
> +docker build -t nomadics/ctrserver:latest .
dont namespace. suggest:
`ctr-psx-server:latest`

2024-06-05 08:56 UTC, aalhendi commented on mods/Windows/OnlineCTR/Network_PC/Server/Dockerfile
> +RUN cd /root/CTR-ModSDK/externals/enet/ && autoreconf -vfi
This `RUN`  block with it's `cd`s can be replaced with something like:

```
WORKDIR /root/CTR-ModSDK/externals/enet/
RUN autoreconf -vfi && chmod +x ./configure && ./configure && make && make install
```

2024-06-05 08:56 UTC, aalhendi commented on mods/Windows/OnlineCTR/Network_PC/Server/Dockerfile
> +RUN cd /root/CTR-ModSDK/externals/enet/ && cmake CMakeLists.txt
cmake not needed. autoreconf/configure takes care of this

2024-06-05 08:56 UTC, aalhendi commented on mods/Windows/OnlineCTR/Network_PC/Server/Dockerfile
> +RUN cd /root/CTR-ModSDK/mods/Windows/OnlineCTR/Network_PC/Server/
once again, we can make use of `WORKDIR`:

```
WORKDIR /root/CTR-ModSDK/mods/Windows/OnlineCTR/Network_PC/Server/
RUN cmake CMakeLists.txt && make
```

2024-06-05 08:56 UTC, aalhendi commented on mods/Windows/OnlineCTR/Network_PC/Server/buildDocker.sh
> +cp -r ../../../../../externals/enet/ .
careful with context! Trailing `/` copies directory _contents_ and not the actual directory
``cp -r ../../../../../externals/enet .``
``cp -r ../../../../../decompile . ``

2024-06-05 15:17 UTC, aalhendi approved these changes
LGTM

2024-06-05 17:43 UTC, PedroHLC approved these changes

2024-06-15 01:29 UTC, merged

2024-06-19 10:09 UTC, arthurdenner commented
Thank you to everyone involved in this feature!

@PedroHLC, is the CI pushing a new image to GitHub's registry or is it an idea to be explored/implemented yet?

2024-06-19 16:53 UTC, PedroHLC commented
> is the CI pushing a new image to GitHub's registry or is it an idea to be explored/implemented yet?

Idea